### ISSUE TITLE
`functools.cache` is available only from Python3.9

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha-python#6]
The recent release 2.1 does not seem to work with any python version < 3.9

```
AttributeError: module 'functools' has no attribute 'cache'
```

Solution:
https://stackoverflow.com/a/70301476/

**Comment by virtualvinodh** [comment]
Fixed.
